# Site settings
title: Awesome Zone
email: dalonng@gmail.com
description: > # 版权所有 © 2014-2014 大桥 – dalonng.github.cn.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dalonng.github.com" # the base hostname & protocol for your site
twitter_username: dalonng
github_username:  dalonng

# Build settings
markdown: kramdown

timezone: Asia/Beijing
