# Site settings
title: 滋啦滋啦滋啦文
email: dalonng@gmail.com
author: 大桥
description: > # 版权所有 © 2014-2016 大桥 – dalonng.github.cn.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dalonng.github.com" # the base hostname & protocol for your site
twitter_username: dalonng
github_username:  dalonng

# Build settings
markdown: kramdown

timezone: Asia/Beijing
